---

- name: Package prerequisites for node.js
  action: apt pkg=python-software-properties state=installed

- name: Add the node.js PPA
  action: command add-apt-repository -y ppa:chris-lea/node.js creates=/etc/apt/sources.list.d/chris-lea-node_js-quantal.list

- name: Update the apt cache for the new repository
  action: apt update-cache=yes

- name: Install nodejs and npm
  action: apt pkg={{ item }} state=installed
  with_items:
    - nodejs

- name: Install less compiler
  action: npm name=less global=yes state=latest
  when: include_less == True
