---
- name: ensure python-software-properties is installed
  apt: pkg=python-software-properties state=installed

- name: add the rabbitmq apt key
  action: apt_key url=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present

- name: add rabbitmq official apt repository
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present

- name: Update apt
  apt: update_cache=yes cache_valid_time=3600 upgrade=safe

- name: install rabbitmq
  apt: pkg=rabbitmq-server state=installed force=yes
  notify: restart rabbitmq

# - name: enable rabbitmq plugins
#   rabbitmq_plugin: names=rabbitmq_management,rabbitmq_tracing,rabbitmq_federation state=enabled
#   notify:
#   - restart rabbitmq

# - name: add users
#   rabbitmq_user: user={{item}} password=changeme tags=administrator,{{item}} vhost={{ hostname }} configure_priv=.* write_priv=.* read_priv=.* state=present
#   with_items:
#   - rabbituser

# - name: remove default guest user
#   rabbitmq_user: user=guest state=absent

# - name: ensure vhost /test is present
#   rabbitmq_vhost: name=/test state=present

# Uncomment this to set a specific user for rabbitmq
# - name: set federation local-username
#   rabbitmq_parameter: component=federation name=local-username value='"rabbituser"' state=present
